openapi: 3.2.0
info:
  title: Pineapple Users API
  description: Pineapple
  version: 0.0.1
servers:
- url: http://127.0.0.1:1234/api
security:
- OpenID:
  - openid
  - email
  - profile
- ApiKeyAuth: []
tags:
- name: Users
paths:
  /user/info:
    get:
      tags:
      - Users
      summary: Get user info
      operationId: getUser
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        404:
          description: User not found
        500:
          $ref: '#/components/responses/ServerError'
  /user/tasks:
    get:
      tags:
      - Users
      summary: get user task info
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTasksInfo'
        400:
          $ref: '#/components/responses/RequestError'
        500:
          $ref: '#/components/responses/ServerError'
      operationId: getUserTasks
      x-operation-id-source: derived
  /user/init:
    post:
      tags:
      - Users
      summary: init user
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/RequestError'
        500:
          $ref: '#/components/responses/ServerError'
      operationId: postUserInit
      x-operation-id-source: derived
components:
  schemas:
    ComputeUnitId:
      description: compute unit name
      type: string
      example: 1c-1g
      maxLength: 32
    UserTaskInfo:
      type: object
      properties:
        compute_unit:
          $ref: '#/components/schemas/ComputeUnitId'
        number:
          type: integer
          format: int64
        price:
          type: number
          format: double
    UserTasksInfo:
      type: object
      properties:
        env_num:
          type: integer
          format: int64
        app_num:
          type: integer
          format: int64
        task_list:
          type: array
          items:
            $ref: '#/components/schemas/UserTaskInfo'
    UserInfo:
      type: object
      properties:
        name:
          type: string
          example: John
        balance:
          type: number
          format: double
  responses:
    ServerError:
      description: server error
      content:
        text/plain:
          schema:
            type: string
          example: Something went wrong.
    RequestError:
      description: http request error
      content:
        application/json:
          schema:
            type: object
            properties:
              content:
                type: object
              message:
                type: string
              type:
                type: string
  securitySchemes:
    OpenID:
      type: openIdConnect
      openIdConnectUrl: /.well-known/openid-configuration
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
